<a href="https://colab.research.google.com/github/yashwanthks78/pytorch/blob/main/MNIST_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn
import torch opti
from torchvision import datasets, transforms

In [2]:
dataset = datasets.MNIST(root='./data', train=True, download=True,
                         transform=transforms.ToTensor())

100%|██████████| 9.91M/9.91M [00:01<00:00, 5.04MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 133kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.25MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.19MB/s]


In [4]:
x_train = dataset.data
y_train = dataset.targets

In [5]:
selected_classes = [0, 1, 2]

In [6]:
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    print(indices)

tensor([   1,   21,   34,   37,   51,   56,   63,   68,   69,   75,   81,   88,
          95,  108,  114,  118,  119,  121,  156,  169,  192,  206,  209,  210,
         216,  229,  232,  234,  246,  249,  260,  283,  293,  296,  303,  320,
         326,  359,  399,  427,  429,  435,  440,  451,  453,  458,  462,  464,
         473,  489,  519,  524,  526,  527,  542,  577,  582,  596,  603,  612,
         633,  639,  656,  662,  666,  667,  668,  669,  689,  702,  709,  712,
         733,  743,  745,  776,  781,  787,  790,  818,  825,  849,  859,  860,
         869,  872,  889,  903,  927,  943,  949,  952,  957,  965,  979,  984,
         997, 1000, 1015, 1018])
tensor([  3,   6,   8,  14,  23,  24,  40,  59,  67,  70,  72,  77,  78,  99,
        102, 104, 105, 112, 113, 124, 128, 134, 152, 174, 177, 184, 200, 201,
        205, 208, 211, 224, 231, 248, 251, 269, 270, 276, 290, 309, 310, 315,
        345, 351, 355, 357, 358, 366, 382, 394, 397, 398, 406, 408, 416, 443,
        447, 45

In [7]:
x_final, y_final = [], []
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    x_final.append(x_train[indices])
    y_final.append(y_train[indices])

In [8]:
len(x_final)

3

In [9]:
xx = torch.cat(x_final)
yy = torch.cat(y_final)

In [10]:
yy

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [11]:
from torch.utils.data import TensorDataset, DataLoader

In [28]:
xx = xx.view(xx.size(0), -1).float()
yy = yy.long()


In [29]:
dataset = TensorDataset(xx, yy)
data = DataLoader(dataset, batch_size=32, shuffle=True)

In [12]:
dataset = TensorDataset(xx, yy)

In [13]:
data = DataLoader(dataset, batch_size=32, shuffle=True)

In [30]:
import torch.nn as nn

class MyCNN(nn.Module):
    def __init__(self):
        super(MyCNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        self.fc1 = nn.Linear(32 * 14 * 14, 64)
        self.fc2 = nn.Linear(64, 3)

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.pool(x)

        x = x.view(x.size(0), -1)

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)

        return x


In [31]:
model = MyModel()

In [33]:
model.train()
epochs = 50

for epoch in range(epochs):

    for batch_x, batch_y in data:

        outputs = model(batch_x)
        loss = criterion(outputs, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item()}")



Epoch 1, Loss: 0.024582484737038612
Epoch 2, Loss: 5.254977168078767e-06
Epoch 3, Loss: 0.0
Epoch 4, Loss: 0.0
Epoch 5, Loss: 0.0
Epoch 6, Loss: 1.8874783336286782e-07
Epoch 7, Loss: 0.0
Epoch 8, Loss: 0.0
Epoch 9, Loss: 1.1920920428565296e-07
Epoch 10, Loss: 0.0
Epoch 11, Loss: 0.0
Epoch 12, Loss: 5.960463411724959e-08
Epoch 13, Loss: 1.9868211964535476e-08
Epoch 14, Loss: 0.0
Epoch 15, Loss: 0.0
Epoch 16, Loss: 0.0
Epoch 17, Loss: 0.0
Epoch 18, Loss: 0.0
Epoch 19, Loss: 0.0
Epoch 20, Loss: 0.0
Epoch 21, Loss: 0.0
Epoch 22, Loss: 0.0
Epoch 23, Loss: 0.0
Epoch 24, Loss: 2.9802317058624794e-08
Epoch 25, Loss: 0.0
Epoch 26, Loss: 0.0
Epoch 27, Loss: 0.0
Epoch 28, Loss: 0.0
Epoch 29, Loss: 0.0
Epoch 30, Loss: 0.0
Epoch 31, Loss: 0.0
Epoch 32, Loss: 2.9802317058624794e-08
Epoch 33, Loss: 0.0
Epoch 34, Loss: 0.0
Epoch 35, Loss: 0.0
Epoch 36, Loss: 0.0
Epoch 37, Loss: 0.0
Epoch 38, Loss: 0.0
Epoch 39, Loss: 0.0
Epoch 40, Loss: 1.9868211964535476e-08
Epoch 41, Loss: 0.0
Epoch 42, Loss: 0.0
Ep

In [34]:
model.eval()

sample = xx[0].unsqueeze(0)

with torch.no_grad():
    output = model(sample)
    _, predicted = torch.max(output, 1)

print("Prediction:", predicted.item())

Prediction: 0


In [35]:
print("Predicted:", predicted.item())
print("Actual:", yy[0].item())


Predicted: 0
Actual: 0


In [36]:
torch.save(model.state_dict(), 'model_weights.pth')


In [32]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [14]:
for batch in data:
    print(batch[0].shape)
    break

torch.Size([32, 28, 28])


In [24]:
import torch.nn as nn
from torch.optim import Adam


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = MyModel() # Initialize the model

loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)

In [ ]:
loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)


In [25]:
model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(64*2*2, 128),
    nn.ReLU(),
    nn.Linear(128, 3)
)

In [27]:
loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)

In [20]:
for batch in data:
  batch_x=batch[0]
  batch_y=batch[1]

In [15]:
for batch in data:
  batch_x=batch[0]
  batch_y=batch[1]
  print(batch_x.shape,batch_y.shape)

torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([32, 28, 28]) torch.Size([32])
torch.Size([12, 28, 28]) torch.Size([12])


In [17]:
#torch.save(model.state_dict(),'model_weight.path')

In [18]:
#model=ModelArchitecture()
#model.load_state_dict(torch.load('model_weights.pth'))
#model.eval()

In [ ]:
import torch.nn as nn

class MyCNN(nn.Module):
    def __init__(self):
        super(MyCNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        self.fc1 = nn.Linear(32 * 14 * 14, 64)
        self.fc2 = nn.Linear(64, 3)

    def forward(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.pool(x)

        x = x.view(x.size(0), -1)

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)

        return x
